export const ROUTES = {
    home: "/",
    removeBackground: "/remove-background",
    upscale: "/upscale",
    crop: "/crop",
    editor: "/editor",
    retouch: "/retouch",
    photoGenerator: "/photo-generator",
    compress: "/compress",
    watermarkRemover: "/watermark-remover",
    ocr: "/ocr",
    documents: "/documents",
    pdfMerge: "/pdf/merge",
    pdfSplit: "/pdf/split",
    pdfOrganize: "/pdf/organize",
    pdfRotate: "/pdf/rotate",
    pdfToImages: "/pdf/to-images",
    imagesToPdf: "/pdf/images-to-pdf",
    pdfCompress: "/pdf/compress",
    pdfWatermark: "/pdf/watermark",
    pdfPageNumbers: "/pdf/page-numbers",
    pdfToText: "/pdf/to-text",
    textEditor: "/text/editor",
    textCleaner: "/text/cleaner",
    caseConverter: "/text/case-converter",
    wordCounter: "/text/word-counter",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
